In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch
import numpy as numpy

In [ ]:
array = [[1, 2], [7, 4], [5, 6]]
tensor0 = torch.tensor(array)
print(tensor0)

In [4]:
tensor1 = torch.tensor([[1, 1, 1], [2, 2, 2]])
tensor2 = torch.tensor([[3, 3, 3], [4, 4, 4]])

In [6]:
print(tensor1[:2])
print(tensor1[:, :2])

tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([[1, 1],
        [2, 2]])


In [7]:
#Vertical concatination
concat_1 = torch.cat([tensor1, tensor2])
print(concat_1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [8]:
#Horizontal concatenation
concat_2 = torch.cat([tensor1, tensor2], dim=1)
print(concat_2)

tensor([[1, 1, 1, 3, 3, 3],
        [2, 2, 2, 4, 4, 4]])
